### ISSUE TITLE
FalixNodes is not allowing Chunky to be installed

### ISSUE THREAD

**Issue by IkyMax** [pop4959/Chunky#260] opened 2023-04-15 04:02 UTC
I used the plugin on my server (Falixnode) chunky 1.3.52 but today I tried to power the server on and this happened:

`container@pterodactyl~ Server marked as offline...
[Falix Panel]: Checking for unused resources to be assigned for your server....
[Falix Panel]: Updating configuration...
[Falix Panel]: Making sure your server is ready to run...
container@pterodactyl~ Server marked as starting...
[Falix Panel]: Setting up safe environment for your server...
[Falix Panel]: Finished setting up safe environment.
Found server.jar
===============================
One of your installed plugins are not allowed.
Please remove this plugin:
- /home/container/plugins/Chunky-1.3.52.jar
===============================
container@pterodactyl~ Server marked as offline...`

**Comment by pop4959** [comment] 2023-04-15 04:32
Hi, thank you for bringing this to my attention! I will try to contact them to see what this is about. Chunky is a safe plugin to use, so I'm not sure why any host would be blocking it.

**Comment by IkyMax** [comment] 2023-04-17 06:48
Okay! keep me updated!

**Comment by pop4959** [comment] 2023-04-17 21:13
In discussions with them currently. I've given them a solution to the problem they seem to be having, and my hope it that it works or we can make some adjustments to make it work for them.

**Comment by pop4959** [comment] 2023-04-23 09:49
@IkyMax Hi, can you check if this is now resolved? I provided them with a solution and my ticket with them was closed, so I assume this should be all good now.

**Comment by IkyMax** [comment] 2023-04-24 05:21
Hi! i tried today and it stills give me the same error!

**Comment by pop4959** [comment] 2023-04-24 05:23
Thanks for letting me know, check again in a few days just to be sure but otherwise I will contact them again in a week since I'm currently on vacation (so I can't do much more until then to help resolve this).

You can also try reaching out to their support yourself to remind them to fix this.

**Comment by devil38** [comment] 2023-04-24 15:15
Hello
I am maintainer of pterodactyl egg at falix
Plugin have been unblocked

**Comment by pop4959** [comment] 2023-04-24 18:54
Thank you! Appreciate the quick response.

@IkyMax Can you double check that this is resolved? I am not able to check currently. Will close this issue once confirmed.

**Comment by pop4959** [comment] 2023-04-29 21:29
I found time to verify myself that this does appear to be fixed. Thanks again @devil38 for you help, please feel free to reach out if there is anything else I can help Falix with should there ever be any other issues with chunky on your service.

**Closed by pop4959** 2023-04-29 21:29 UTC
Labels: question
