### ISSUE TITLE
No configuration settings for chunk generation rate - causes crashes

### ISSUE THREAD

**Issue by AndrewBarrell1** [pop4959/Chunky#264] opened 2023-04-27 13:40 UTC
Chunky doesn't seem to have configuration settings for how to slow down the generation of chunks.

Letting it go off on its own causes a crash within a few minutes so I need to pause it, let the server catch up, then resume.

It would be really nice if this could be slowed down as an input parameter in some way.

**Comment by pop4959** [comment] 2023-04-29 21:04
Hi, sorry for the slow response as I have been busy.

Chunk generation rate automatically scales with your hardware, so it's unlikely to run too fast. If you have evidence to suggest otherwise, I would love to see it. Normally, crashes are caused by a variety of other reasons and are unrelated.

For troubleshooting, please join the [Discord server](https://discord.gg/ZwVJukcNQG) first and join the chunky support channel. Any logs, crash reports, or additional information you would like to share are appreciated. I'm happy to help with resolving crashing any other instability issues which typically are more frequent during processes such as pre-generation.

**Closed by pop4959** 2023-04-29 21:04 UTC
Labels: question
