### ISSUE TITLE
Limited to 3 tasks at a time?

### ISSUE THREAD

**Issue by InfinityZ25** [pop4959/Chunky#48] opened 2020-10-13 16:21 UTC
Hey,

I created a fork of Chunky in which I added a command to check the current status of each running tasks and events to notify when a task is completed or cancelled. I planned to use Chunky to batch pre-generate lots of worlds with 96vcpu at a time. Problem is, I tested it with 36 cpus and it doesn't scale well... 
It only uses about 6 vcpus (2 per world task), and won't use anymore. I queued up 5 different world tasks and only 5 are running and the other two won't start until either of the three get completed. Seems to me like a hard limit but can't find it on code.

Here's a graph of cpu usage 
![image](https://user-images.githubusercontent.com/37850007/95887876-5cc5a900-0d4e-11eb-8aae-31bd4a554b5e.png)

And here is the in game status 
![image](https://user-images.githubusercontent.com/37850007/95887924-6c44f200-0d4e-11eb-8381-46bbba17ac8b.png)

Clearly, It doesn't want to even start uhc5 and uhc4 tasks.

To be clear, I also tried it in the latest upstream commit, not my fork, and had the same results. Only three tasks would spam the console.

**Comment by pop4959** [comment] 2020-10-13 19:22
Hi, first of all it's very cool to hear you've forked Chunky to get it to do something specific on your server. Eventually I'd like to add some proper API but I'm not willing to commit to anything yet since I'm still looking to make a few more revisions of the current code.

As for your issue... very strange, there is theoretically no limit to the number of worlds supported. Chunky currently only limits generation to 1 task per world, since Minecraft handles generation on a per-world basis (thus running 2 in the same world simultaneously yields no benefit). However, you *should* be able to run tasks in as many worlds simultaneously as you'd like, one at a time.

I've tested running 5 worlds simultaneously by creating them using Multiverse first, and it seems to be working on my end (besides pegging all of the cores on my 3700x):
<https://paste.ubuntu.com/p/k9t9zXpjv8/>

My guess is that there is something else limiting you to 3 worlds. Maybe try testing temporarily on an unmodified Paper server to see if you get the same results or not.

**Comment by pop4959** [comment] 2020-10-19 20:06
Any new discovery?

**Comment by InfinityZ25** [comment] 2020-10-19 20:21
Been really busy. Haven’t been able to continue working on this side of the
project, thus no new discoveries yet. Will keep you posted. Might ping you
in discord

**Comment by pop4959** [comment] 2020-10-19 20:30
No problem. Let's continue on Discord then; feel free to ping. Since I'm not able to reproduce this on the release version of Chunky I will close this issue for now though.

**Closed by pop4959** 2020-10-19 20:30 UTC
Labels: problem
